Cypress.on('window:before:load', windows => {

})
describe('Projetos - Testa Pagina Analises.cy', function() {
    const THREE_SECONDS_IN_ML = 3000
      beforeEach(function() {
       })
      
      it('Verifica Tela de logon SALES - faz login e logof', function() {
        cy.login()
        cy.get('.mat-expansion-panel-header-title > .open').click()
        cy.get(':nth-child(1) > .mat-list-item > .mat-list-item-content > .mat-list-text > span').click()
        cy.get('.xng-breadcrumb-link').should('have.text', 'Projetos').and('be.visible')
        cy.get('.xng-breadcrumb-trail').should('have.text', 'Análises').and('be.visible')
        cy.get('h2').should('contain', ' Projetos enviados anteriormente').and('be.visible')
        cy.get('p').should('have.text', 'Abaixo listamos suas últimas analises').and('be.visible')
        cy.get('#mat-input-2').should('be.visible')
        cy.get('.mat-form-field-suffix > .mat-icon').should('be.visible')
        cy.get('tr > :nth-child(1)').should('have.text', ' ARQUIVO ').and('be.visible')
        cy.get('tr > :nth-child(2)').should('have.text', ' ORIGEM ').and('be.visible')
        cy.get('tr > :nth-child(3)').should('have.text', 'ID').and('be.visible')
        cy.get('tr > :nth-child(4)').should('have.text', ' DATA ').and('be.visible')
        //cy.get('tr > :nth-child(5)').should('have.text', ' STATUS/AÇÃO ').and('be.visible')
        cy.get(':nth-child(2) > :nth-child(1) > .text').should('be.visible')
        cy.get(':nth-child(2) > :nth-child(2) > .text').should('be.visible')
        cy.get(':nth-child(2) > :nth-child(3) > .text').should('be.visible')
        cy.get(':nth-child(2) > :nth-child(4) > .text').should('be.visible')
        cy.get(':nth-child(2) > .status > div > .stats > .mat-button-wrapper')
        cy.get('tbody:nth-child(2)').should('be.visible')            
        cy.get(':nth-child(3) > :nth-child(1) > .text').should('be.visible')
        cy.get(':nth-child(3) > :nth-child(2) > .text').should('be.visible')
        cy.get(':nth-child(3) > :nth-child(3) > .text').should('be.visible')
        cy.get(':nth-child(3) > :nth-child(4) > .text').should('be.visible')
        cy.get(':nth-child(3) > .status > div > .stats > .mat-button-wrapper')
        cy.get('tbody:nth-child(3)').should('be.visible') 
        cy.get(':nth-child(4) > :nth-child(1) > .text').should('be.visible')
        cy.get(':nth-child(4) > :nth-child(2) > .text').should('be.visible')
        cy.get(':nth-child(4) > :nth-child(3) > .text').should('be.visible')
        cy.get(':nth-child(4) > :nth-child(4) > .text').should('be.visible')
        cy.get(':nth-child(4) > .status > div > .stats > .mat-button-wrapper')
        cy.get('tbody:nth-child(4)').should('be.visible') 
        cy.get(':nth-child(5) > :nth-child(1) > .text').should('be.visible')
        cy.get(':nth-child(5) > :nth-child(2) > .text').should('be.visible')
        cy.get(':nth-child(5) > :nth-child(3) > .text').should('be.visible')
        cy.get(':nth-child(5) > :nth-child(4) > .text').should('be.visible')
        cy.get(':nth-child(5) > .status > div > .stats > .mat-button-wrapper')
        cy.get('tbody:nth-child(5)').should('be.visible') 
        cy.get(':nth-child(6) > :nth-child(1) > .text').should('be.visible')
        cy.get(':nth-child(6) > :nth-child(2) > .text').should('be.visible')
        cy.get(':nth-child(6) > :nth-child(3) > .text').should('be.visible')
        cy.get(':nth-child(6) > :nth-child(4) > .text').should('be.visible')
        cy.get(':nth-child(6) > .status > div > .stats > .mat-button-wrapper')
        cy.get('tbody:nth-child(6)').should('be.visible') 
        cy.get(':nth-child(7) > :nth-child(1) > .text').should('be.visible')
        cy.get(':nth-child(7) > :nth-child(2) > .text').should('be.visible')
        cy.get(':nth-child(7) > :nth-child(3) > .text').should('be.visible')
        cy.get(':nth-child(7) > :nth-child(4) > .text').should('be.visible')
        cy.get(':nth-child(7) > .status > div > .stats > .mat-button-wrapper')
        cy.get('tbody:nth-child(7)').should('be.visible') 
        cy.get(':nth-child(8) > :nth-child(1) > .text').should('be.visible')
        cy.get(':nth-child(8) > :nth-child(2) > .text').should('be.visible')
        cy.get(':nth-child(8) > :nth-child(3) > .text').should('be.visible')
        cy.get(':nth-child(8) > :nth-child(4) > .text').should('be.visible')
        cy.get(':nth-child(8) > .status > div > .stats > .mat-button-wrapper')
        cy.get('tbody:nth-child(8)').should('be.visible') 
        cy.get(':nth-child(9) > :nth-child(1) > .text').should('be.visible')
        cy.get(':nth-child(9) > :nth-child(2) > .text').should('be.visible')
        cy.get(':nth-child(9) > :nth-child(3) > .text').should('be.visible')
        cy.get(':nth-child(9) > :nth-child(4) > .text').should('be.visible')
        cy.get(':nth-child(9) > .status > div > .stats > .mat-button-wrapper')
        cy.get('tbody:nth-child(9)').should('be.visible') 
        cy.get(':nth-child(10) > :nth-child(1) > .text').should('be.visible')
        cy.get(':nth-child(10) > :nth-child(2) > .text').should('be.visible')
        cy.get(':nth-child(10) > :nth-child(3) > .text').should('be.visible')
        cy.get(':nth-child(10) > :nth-child(4) > .text').should('be.visible')
        cy.get(':nth-child(10) > .status > div > .stats > .mat-button-wrapper')
        cy.get('tbody:nth-child(10)').should('be.visible') 
        cy.get(':nth-child(11) > :nth-child(1) > .text').should('be.visible')
        cy.get(':nth-child(11) > :nth-child(2) > .text').should('be.visible')
        cy.get(':nth-child(11) > :nth-child(3) > .text').should('be.visible')
        cy.get(':nth-child(11) > :nth-child(4) > .text').should('be.visible')
        cy.get(':nth-child(11) > .status > div > .stats > .mat-button-wrapper')
        cy.get('tbody:nth-child(11)').should('be.visible') 
        cy.get('.options > div > span').should('be.visible')
        cy.get(':nth-child(3) > .mat-icon').should('be.visible').click()
        cy.get(':nth-child(1) > .text').should('be.visible')
        cy.get(':nth-child(2) > .text').should('be.visible')
        cy.get(':nth-child(3) > .text').should('be.visible')
        cy.get(':nth-child(4) > .text').should('be.visible')
        cy.get(':nth-child(1) > .mat-icon').should('be.visible').click()

        cy.Sair()
        
      })
})